server:
  port: 8088

token:
  secretKey: jkfdsnleds
  expireSec: 3600000
  header: JWTHeaderName
spring:
  profiles:
    active: @spring.profiles.active@


mybatis:
  mapper-locations:
    - dao/*.xml

